# Generated by Django 3.0.7 on 2020-06-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TaskField',
            new_name='TaskList',
        ),
    ]
